### ISSUE TITLE
Would the Auth Class interfere with Laravels Basic Auth setup?

### ISSUE THREAD

**Issue by StuartRus** [andrewmile/FMLaravel#2]
Hi Andrew, 
Thank you so much for making this connector. :)
Sorry im still finding my way through Laravel so it may be a silly question but will your Auth class work with having the Basic Auth that is boxed with L5 doing a simple login/signup? 
I was thinking to have mysql to handle the user sign up/login and then after authenticated use the Filemaker DB to retrieve the data. 
I have worked out how to have 2 DB's but i'm not getting the authenticated user using Auth::user()

what is your suggestion?

**Comment by andrewmile** [comment]
Hi,
I'm glad you're getting use out of the package!  The included FMLaravel Auth driver is completely optional so if you want to use MySQL you can just use Laravel's Auth driver.  If you are using filemaker as your database driver in config/database.php you will need to override that for your user model in order to query Auth::user().  You can do this by adding the following to your user.php model:

```
protected $connection = 'mysql';
```

Please let me know if that works for you.
